#负责编译user目录下的源文件
CC=gcc
CC_FLAGS=-lunix_lib -lpthread
OUTPUT=bin/ls \
	   bin/cp

all:$(OUTPUT)

###########################
bin/ls:src/ls.c
	$(CC) $^ -o $@ $(CC_FLAGS)

bin/cp:src/cp.c
	$(CC) $^ -o $@ $(CC_FLAGS)

