#负责编译user目录下的源文件
CC=gcc
CC_FLAGS=-L/home/fenghan/local/unix_lib -lunix_lib -lpthread
OUTPUT=user/bin/ls \
	   user/bin/cp

all:$(OUTPUT)

###########################
user/bin/ls:user/lib/ls.c
	$(CC) $^ -o $@ $(CC_FLAGS)

user/bin/cp:user/lib/cp.c
	$(CC) $^ -o $@ $(CC_FLAGS)

