CC=gcc
CC_FLAGS=-I .
OUTPUT=user/bin/ls \
	   user/bin/cp

all:$(OUTPUT)

###########################
user/bin/ls:user/lib/ls.c
	$(CC) $(CC_FLAGS) $^ -o $@

user/bin/cp:user/lib/cp.c
	$(CC) $(CC_FLAGS) $^ -o $@

